### YamlMime:ManagedReference
items:
- uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
  commentId: T:Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
  id: GuildConfigExtensions.GeneratingChannel
  parent: Mewdeko.Database.Extensions
  children:
  - Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.ChannelId
  - Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.GuildId
  langs:
  - csharp
  - vb
  name: GuildConfigExtensions.GeneratingChannel
  nameWithType: GuildConfigExtensions.GeneratingChannel
  fullName: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
  type: Class
  source:
    remote:
      path: src/Mewdeko.Database/Extensions/GuildConfigExtensions.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: GeneratingChannel
    path: src/Mewdeko.Database/Extensions/GuildConfigExtensions.cs
    startLine: 9
  assemblies:
  - Mewdeko.Database
  namespace: Mewdeko.Database.Extensions
  syntax:
    content: public class GuildConfigExtensions.GeneratingChannel
    content.vb: Public Class GuildConfigExtensions.GeneratingChannel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.Mewdeko.Extensions.Extensions.ThrowIfNull``1(System.String)
- uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.GuildId
  commentId: P:Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.GuildId
  id: GuildId
  parent: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
  langs:
  - csharp
  - vb
  name: GuildId
  nameWithType: GuildConfigExtensions.GeneratingChannel.GuildId
  fullName: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.GuildId
  type: Property
  source:
    remote:
      path: src/Mewdeko.Database/Extensions/GuildConfigExtensions.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: GuildId
    path: src/Mewdeko.Database/Extensions/GuildConfigExtensions.cs
    startLine: 11
  assemblies:
  - Mewdeko.Database
  namespace: Mewdeko.Database.Extensions
  syntax:
    content: public ulong GuildId { get; set; }
    parameters: []
    return:
      type: System.UInt64
    content.vb: Public Property GuildId As ULong
  overload: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.GuildId*
- uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.ChannelId
  commentId: P:Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.ChannelId
  id: ChannelId
  parent: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
  langs:
  - csharp
  - vb
  name: ChannelId
  nameWithType: GuildConfigExtensions.GeneratingChannel.ChannelId
  fullName: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.ChannelId
  type: Property
  source:
    remote:
      path: src/Mewdeko.Database/Extensions/GuildConfigExtensions.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: ChannelId
    path: src/Mewdeko.Database/Extensions/GuildConfigExtensions.cs
    startLine: 12
  assemblies:
  - Mewdeko.Database
  namespace: Mewdeko.Database.Extensions
  syntax:
    content: public ulong ChannelId { get; set; }
    parameters: []
    return:
      type: System.UInt64
    content.vb: Public Property ChannelId As ULong
  overload: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.ChannelId*
references:
- uid: Mewdeko.Database.Extensions
  commentId: N:Mewdeko.Database.Extensions
  href: Mewdeko.html
  name: Mewdeko.Database.Extensions
  nameWithType: Mewdeko.Database.Extensions
  fullName: Mewdeko.Database.Extensions
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Database
    name: Database
    href: Mewdeko.Database.html
  - name: .
  - uid: Mewdeko.Database.Extensions
    name: Extensions
    href: Mewdeko.Database.Extensions.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Database
    name: Database
    href: Mewdeko.Database.html
  - name: .
  - uid: Mewdeko.Database.Extensions
    name: Extensions
    href: Mewdeko.Database.Extensions.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.Mewdeko.Extensions.Extensions.ThrowIfNull``1(System.String)
  commentId: M:Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  parent: Mewdeko.Extensions.Extensions
  definition: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  name: ThrowIfNull<GeneratingChannel>(GeneratingChannel, string)
  nameWithType: Extensions.ThrowIfNull<GuildConfigExtensions.GeneratingChannel>(GuildConfigExtensions.GeneratingChannel, string)
  fullName: Mewdeko.Extensions.Extensions.ThrowIfNull<Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel>(Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel, string)
  nameWithType.vb: Extensions.ThrowIfNull(Of GuildConfigExtensions.GeneratingChannel)(GuildConfigExtensions.GeneratingChannel, String)
  fullName.vb: Mewdeko.Extensions.Extensions.ThrowIfNull(Of Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel)(Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel, String)
  name.vb: ThrowIfNull(Of GeneratingChannel)(GeneratingChannel, String)
  spec.csharp:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: <
  - uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
    name: GeneratingChannel
    href: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.html
  - name: '>'
  - name: (
  - uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
    name: GeneratingChannel
    href: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.html
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: (
  - name: Of
  - name: " "
  - uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
    name: GeneratingChannel
    href: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.html
  - name: )
  - name: (
  - uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel
    name: GeneratingChannel
    href: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.html
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  commentId: M:Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  isExternal: true
  href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  name: ThrowIfNull<T>(T, string)
  nameWithType: Extensions.ThrowIfNull<T>(T, string)
  fullName: Mewdeko.Extensions.Extensions.ThrowIfNull<T>(T, string)
  nameWithType.vb: Extensions.ThrowIfNull(Of T)(T, String)
  fullName.vb: Mewdeko.Extensions.Extensions.ThrowIfNull(Of T)(T, String)
  name.vb: ThrowIfNull(Of T)(T, String)
  spec.csharp:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Mewdeko.Extensions.Extensions
  commentId: T:Mewdeko.Extensions.Extensions
  parent: Mewdeko.Extensions
  href: Mewdeko.Extensions.Extensions.html
  name: Extensions
  nameWithType: Extensions
  fullName: Mewdeko.Extensions.Extensions
- uid: Mewdeko.Extensions
  commentId: N:Mewdeko.Extensions
  href: Mewdeko.html
  name: Mewdeko.Extensions
  nameWithType: Mewdeko.Extensions
  fullName: Mewdeko.Extensions
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Extensions
    name: Extensions
    href: Mewdeko.Extensions.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Extensions
    name: Extensions
    href: Mewdeko.Extensions.html
- uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.GuildId*
  commentId: Overload:Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.GuildId
  href: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.html#Mewdeko_Database_Extensions_GuildConfigExtensions_GeneratingChannel_GuildId
  name: GuildId
  nameWithType: GuildConfigExtensions.GeneratingChannel.GuildId
  fullName: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.GuildId
- uid: System.UInt64
  commentId: T:System.UInt64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint64
  name: ulong
  nameWithType: ulong
  fullName: ulong
  nameWithType.vb: ULong
  fullName.vb: ULong
  name.vb: ULong
- uid: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.ChannelId*
  commentId: Overload:Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.ChannelId
  href: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.html#Mewdeko_Database_Extensions_GuildConfigExtensions_GeneratingChannel_ChannelId
  name: ChannelId
  nameWithType: GuildConfigExtensions.GeneratingChannel.ChannelId
  fullName: Mewdeko.Database.Extensions.GuildConfigExtensions.GeneratingChannel.ChannelId
