### YamlMime:ManagedReference
items:
- uid: Mewdeko.Database.Models.CtApplicationCommandType
  commentId: T:Mewdeko.Database.Models.CtApplicationCommandType
  id: CtApplicationCommandType
  parent: Mewdeko.Database.Models
  children:
  - Mewdeko.Database.Models.CtApplicationCommandType.Message
  - Mewdeko.Database.Models.CtApplicationCommandType.None
  - Mewdeko.Database.Models.CtApplicationCommandType.Slash
  - Mewdeko.Database.Models.CtApplicationCommandType.User
  langs:
  - csharp
  - vb
  name: CtApplicationCommandType
  nameWithType: CtApplicationCommandType
  fullName: Mewdeko.Database.Models.CtApplicationCommandType
  type: Enum
  source:
    remote:
      path: src/Mewdeko.Database/Models/ChatTriggers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: CtApplicationCommandType
    path: src/Mewdeko.Database/Models/ChatTriggers.cs
    startLine: 59
  assemblies:
  - Mewdeko.Database
  namespace: Mewdeko.Database.Models
  syntax:
    content: public enum CtApplicationCommandType
    content.vb: Public Enum CtApplicationCommandType
- uid: Mewdeko.Database.Models.CtApplicationCommandType.None
  commentId: F:Mewdeko.Database.Models.CtApplicationCommandType.None
  id: None
  parent: Mewdeko.Database.Models.CtApplicationCommandType
  langs:
  - csharp
  - vb
  name: None
  nameWithType: CtApplicationCommandType.None
  fullName: Mewdeko.Database.Models.CtApplicationCommandType.None
  type: Field
  source:
    remote:
      path: src/Mewdeko.Database/Models/ChatTriggers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: None
    path: src/Mewdeko.Database/Models/ChatTriggers.cs
    startLine: 61
  assemblies:
  - Mewdeko.Database
  namespace: Mewdeko.Database.Models
  syntax:
    content: None = 0
    return:
      type: Mewdeko.Database.Models.CtApplicationCommandType
- uid: Mewdeko.Database.Models.CtApplicationCommandType.Slash
  commentId: F:Mewdeko.Database.Models.CtApplicationCommandType.Slash
  id: Slash
  parent: Mewdeko.Database.Models.CtApplicationCommandType
  langs:
  - csharp
  - vb
  name: Slash
  nameWithType: CtApplicationCommandType.Slash
  fullName: Mewdeko.Database.Models.CtApplicationCommandType.Slash
  type: Field
  source:
    remote:
      path: src/Mewdeko.Database/Models/ChatTriggers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: Slash
    path: src/Mewdeko.Database/Models/ChatTriggers.cs
    startLine: 62
  assemblies:
  - Mewdeko.Database
  namespace: Mewdeko.Database.Models
  syntax:
    content: Slash = 1
    return:
      type: Mewdeko.Database.Models.CtApplicationCommandType
- uid: Mewdeko.Database.Models.CtApplicationCommandType.Message
  commentId: F:Mewdeko.Database.Models.CtApplicationCommandType.Message
  id: Message
  parent: Mewdeko.Database.Models.CtApplicationCommandType
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: CtApplicationCommandType.Message
  fullName: Mewdeko.Database.Models.CtApplicationCommandType.Message
  type: Field
  source:
    remote:
      path: src/Mewdeko.Database/Models/ChatTriggers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: Message
    path: src/Mewdeko.Database/Models/ChatTriggers.cs
    startLine: 63
  assemblies:
  - Mewdeko.Database
  namespace: Mewdeko.Database.Models
  syntax:
    content: Message = 2
    return:
      type: Mewdeko.Database.Models.CtApplicationCommandType
- uid: Mewdeko.Database.Models.CtApplicationCommandType.User
  commentId: F:Mewdeko.Database.Models.CtApplicationCommandType.User
  id: User
  parent: Mewdeko.Database.Models.CtApplicationCommandType
  langs:
  - csharp
  - vb
  name: User
  nameWithType: CtApplicationCommandType.User
  fullName: Mewdeko.Database.Models.CtApplicationCommandType.User
  type: Field
  source:
    remote:
      path: src/Mewdeko.Database/Models/ChatTriggers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: User
    path: src/Mewdeko.Database/Models/ChatTriggers.cs
    startLine: 64
  assemblies:
  - Mewdeko.Database
  namespace: Mewdeko.Database.Models
  syntax:
    content: User = 3
    return:
      type: Mewdeko.Database.Models.CtApplicationCommandType
references:
- uid: Mewdeko.Database.Models
  commentId: N:Mewdeko.Database.Models
  href: Mewdeko.html
  name: Mewdeko.Database.Models
  nameWithType: Mewdeko.Database.Models
  fullName: Mewdeko.Database.Models
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Database
    name: Database
    href: Mewdeko.Database.html
  - name: .
  - uid: Mewdeko.Database.Models
    name: Models
    href: Mewdeko.Database.Models.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Database
    name: Database
    href: Mewdeko.Database.html
  - name: .
  - uid: Mewdeko.Database.Models
    name: Models
    href: Mewdeko.Database.Models.html
- uid: Mewdeko.Database.Models.CtApplicationCommandType
  commentId: T:Mewdeko.Database.Models.CtApplicationCommandType
  parent: Mewdeko.Database.Models
  href: Mewdeko.Database.Models.CtApplicationCommandType.html
  name: CtApplicationCommandType
  nameWithType: CtApplicationCommandType
  fullName: Mewdeko.Database.Models.CtApplicationCommandType
