### YamlMime:ManagedReference
items:
- uid: Mewdeko.Common.Configs
  commentId: N:Mewdeko.Common.Configs
  id: Configs
  parent: Mewdeko.Common
  children:
  - Mewdeko.Common.Configs.BlockedConfig
  - Mewdeko.Common.Configs.BotConfig
  - Mewdeko.Common.Configs.ColorConfig
  - Mewdeko.Common.Configs.ConsoleOutputType
  - Mewdeko.Common.Configs.IConfigSeria
  - Mewdeko.Common.Configs.UpdateCheckType
  langs:
  - csharp
  - vb
  name: Mewdeko.Common.Configs
  nameWithType: Mewdeko.Common.Configs
  fullName: Mewdeko.Common.Configs
  type: Namespace
  assemblies:
  - Mewdeko
references:
- uid: Mewdeko.Common.Configs.BlockedConfig
  commentId: T:Mewdeko.Common.Configs.BlockedConfig
  parent: Mewdeko.Common.Configs
  href: Mewdeko.Common.Configs.BlockedConfig.html
  name: BlockedConfig
  nameWithType: BlockedConfig
  fullName: Mewdeko.Common.Configs.BlockedConfig
- uid: Mewdeko.Common.Configs.BotConfig
  commentId: T:Mewdeko.Common.Configs.BotConfig
  href: Mewdeko.Common.Configs.BotConfig.html
  name: BotConfig
  nameWithType: BotConfig
  fullName: Mewdeko.Common.Configs.BotConfig
- uid: Mewdeko.Common.Configs.ColorConfig
  commentId: T:Mewdeko.Common.Configs.ColorConfig
  parent: Mewdeko.Common.Configs
  href: Mewdeko.Common.Configs.ColorConfig.html
  name: ColorConfig
  nameWithType: ColorConfig
  fullName: Mewdeko.Common.Configs.ColorConfig
- uid: Mewdeko.Common.Configs.ConsoleOutputType
  commentId: T:Mewdeko.Common.Configs.ConsoleOutputType
  parent: Mewdeko.Common.Configs
  href: Mewdeko.Common.Configs.ConsoleOutputType.html
  name: ConsoleOutputType
  nameWithType: ConsoleOutputType
  fullName: Mewdeko.Common.Configs.ConsoleOutputType
- uid: Mewdeko.Common.Configs.IConfigSeria
  commentId: T:Mewdeko.Common.Configs.IConfigSeria
  parent: Mewdeko.Common.Configs
  href: Mewdeko.Common.Configs.IConfigSeria.html
  name: IConfigSeria
  nameWithType: IConfigSeria
  fullName: Mewdeko.Common.Configs.IConfigSeria
- uid: Mewdeko.Common.Configs.UpdateCheckType
  commentId: T:Mewdeko.Common.Configs.UpdateCheckType
  parent: Mewdeko.Common.Configs
  href: Mewdeko.Common.Configs.UpdateCheckType.html
  name: UpdateCheckType
  nameWithType: UpdateCheckType
  fullName: Mewdeko.Common.Configs.UpdateCheckType
- uid: Mewdeko.Common.Configs
  commentId: N:Mewdeko.Common.Configs
  href: Mewdeko.html
  name: Mewdeko.Common.Configs
  nameWithType: Mewdeko.Common.Configs
  fullName: Mewdeko.Common.Configs
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Common
    name: Common
    href: Mewdeko.Common.html
  - name: .
  - uid: Mewdeko.Common.Configs
    name: Configs
    href: Mewdeko.Common.Configs.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Common
    name: Common
    href: Mewdeko.Common.html
  - name: .
  - uid: Mewdeko.Common.Configs
    name: Configs
    href: Mewdeko.Common.Configs.html
