### YamlMime:ManagedReference
items:
- uid: Mewdeko.Services.Settings.ConfigParsers
  commentId: T:Mewdeko.Services.Settings.ConfigParsers
  id: ConfigParsers
  parent: Mewdeko.Services.Settings
  children:
  - Mewdeko.Services.Settings.ConfigParsers.Culture(System.String,System.Globalization.CultureInfo@)
  - Mewdeko.Services.Settings.ConfigParsers.String(System.String,System.String@)
  langs:
  - csharp
  - vb
  name: ConfigParsers
  nameWithType: ConfigParsers
  fullName: Mewdeko.Services.Settings.ConfigParsers
  type: Class
  source:
    remote:
      path: src/Mewdeko/Services/Settings/ConfigParsers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: ConfigParsers
    path: src/Mewdeko/Services/Settings/ConfigParsers.cs
    startLine: 8
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services.Settings
  summary: Custom setting value parsers for types which don't have them by default
  example: []
  syntax:
    content: public static class ConfigParsers
    content.vb: Public Module ConfigParsers
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Mewdeko.Services.Settings.ConfigParsers.String(System.String,System.String@)
  commentId: M:Mewdeko.Services.Settings.ConfigParsers.String(System.String,System.String@)
  id: String(System.String,System.String@)
  parent: Mewdeko.Services.Settings.ConfigParsers
  langs:
  - csharp
  - vb
  name: String(string, out string)
  nameWithType: ConfigParsers.String(string, out string)
  fullName: Mewdeko.Services.Settings.ConfigParsers.String(string, out string)
  type: Method
  source:
    remote:
      path: src/Mewdeko/Services/Settings/ConfigParsers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: String
    path: src/Mewdeko/Services/Settings/ConfigParsers.cs
    startLine: 13
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services.Settings
  summary: Default string parser. Passes input to output and returns true.
  example: []
  syntax:
    content: public static bool String(string input, out string output)
    parameters:
    - id: input
      type: System.String
    - id: output
      type: System.String
    return:
      type: System.Boolean
    content.vb: Public Shared Function [String](input As String, output As String) As Boolean
  overload: Mewdeko.Services.Settings.ConfigParsers.String*
  nameWithType.vb: ConfigParsers.String(String, String)
  fullName.vb: Mewdeko.Services.Settings.ConfigParsers.String(String, String)
  name.vb: String(String, String)
- uid: Mewdeko.Services.Settings.ConfigParsers.Culture(System.String,System.Globalization.CultureInfo@)
  commentId: M:Mewdeko.Services.Settings.ConfigParsers.Culture(System.String,System.Globalization.CultureInfo@)
  id: Culture(System.String,System.Globalization.CultureInfo@)
  parent: Mewdeko.Services.Settings.ConfigParsers
  langs:
  - csharp
  - vb
  name: Culture(string, out CultureInfo)
  nameWithType: ConfigParsers.Culture(string, out CultureInfo)
  fullName: Mewdeko.Services.Settings.ConfigParsers.Culture(string, out System.Globalization.CultureInfo)
  type: Method
  source:
    remote:
      path: src/Mewdeko/Services/Settings/ConfigParsers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: Culture
    path: src/Mewdeko/Services/Settings/ConfigParsers.cs
    startLine: 25
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services.Settings
  summary: Parses the input string into a CultureInfo object.
  example: []
  syntax:
    content: public static bool Culture(string input, out CultureInfo output)
    parameters:
    - id: input
      type: System.String
      description: The input string representing a culture.
    - id: output
      type: System.Globalization.CultureInfo
      description: The parsed CultureInfo object.
    return:
      type: System.Boolean
      description: True if parsing is successful, otherwise false.
    content.vb: Public Shared Function Culture(input As String, output As CultureInfo) As Boolean
  overload: Mewdeko.Services.Settings.ConfigParsers.Culture*
  nameWithType.vb: ConfigParsers.Culture(String, CultureInfo)
  fullName.vb: Mewdeko.Services.Settings.ConfigParsers.Culture(String, System.Globalization.CultureInfo)
  name.vb: Culture(String, CultureInfo)
references:
- uid: Mewdeko.Services.Settings
  commentId: N:Mewdeko.Services.Settings
  href: Mewdeko.html
  name: Mewdeko.Services.Settings
  nameWithType: Mewdeko.Services.Settings
  fullName: Mewdeko.Services.Settings
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Services
    name: Services
    href: Mewdeko.Services.html
  - name: .
  - uid: Mewdeko.Services.Settings
    name: Settings
    href: Mewdeko.Services.Settings.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Services
    name: Services
    href: Mewdeko.Services.html
  - name: .
  - uid: Mewdeko.Services.Settings
    name: Settings
    href: Mewdeko.Services.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Mewdeko.Services.Settings.ConfigParsers.String*
  commentId: Overload:Mewdeko.Services.Settings.ConfigParsers.String
  href: Mewdeko.Services.Settings.ConfigParsers.html#Mewdeko_Services_Settings_ConfigParsers_String_System_String_System_String__
  name: String
  nameWithType: ConfigParsers.String
  fullName: Mewdeko.Services.Settings.ConfigParsers.String
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Mewdeko.Services.Settings.ConfigParsers.Culture*
  commentId: Overload:Mewdeko.Services.Settings.ConfigParsers.Culture
  href: Mewdeko.Services.Settings.ConfigParsers.html#Mewdeko_Services_Settings_ConfigParsers_Culture_System_String_System_Globalization_CultureInfo__
  name: Culture
  nameWithType: ConfigParsers.Culture
  fullName: Mewdeko.Services.Settings.ConfigParsers.Culture
- uid: System.Globalization.CultureInfo
  commentId: T:System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.globalization.cultureinfo
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Globalization
  commentId: N:System.Globalization
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Globalization
  nameWithType: System.Globalization
  fullName: System.Globalization
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Globalization
    name: Globalization
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.globalization
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Globalization
    name: Globalization
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.globalization
