### YamlMime:ManagedReference
items:
- uid: Mewdeko.Modules.Games.Common.TriviaConfig
  commentId: T:Mewdeko.Modules.Games.Common.TriviaConfig
  id: TriviaConfig
  parent: Mewdeko.Modules.Games.Common
  children:
  - Mewdeko.Modules.Games.Common.TriviaConfig.CurrencyReward
  - Mewdeko.Modules.Games.Common.TriviaConfig.MinimumWinReq
  langs:
  - csharp
  - vb
  name: TriviaConfig
  nameWithType: TriviaConfig
  fullName: Mewdeko.Modules.Games.Common.TriviaConfig
  type: Class
  source:
    remote:
      path: src/Mewdeko/Modules/Games/Common/GamesConfig.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: TriviaConfig
    path: src/Mewdeko/Modules/Games/Common/GamesConfig.cs
    startLine: 55
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Modules.Games.Common
  summary: Configuration settings for trivia games.
  example: []
  syntax:
    content: public sealed class TriviaConfig
    content.vb: Public NotInheritable Class TriviaConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - Mewdeko.Modules.Games.Common.TriviaConfig.Mewdeko.Extensions.Extensions.ThrowIfNull``1(System.String)
- uid: Mewdeko.Modules.Games.Common.TriviaConfig.CurrencyReward
  commentId: P:Mewdeko.Modules.Games.Common.TriviaConfig.CurrencyReward
  id: CurrencyReward
  parent: Mewdeko.Modules.Games.Common.TriviaConfig
  langs:
  - csharp
  - vb
  name: CurrencyReward
  nameWithType: TriviaConfig.CurrencyReward
  fullName: Mewdeko.Modules.Games.Common.TriviaConfig.CurrencyReward
  type: Property
  source:
    remote:
      path: src/Mewdeko/Modules/Games/Common/GamesConfig.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: CurrencyReward
    path: src/Mewdeko/Modules/Games/Common/GamesConfig.cs
    startLine: 60
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Modules.Games.Common
  summary: The amount of currency awarded to the winner of the trivia game.
  example: []
  syntax:
    content: >-
      [Comment("The amount of currency awarded to the winner of the trivia game.")]

      public long CurrencyReward { get; set; }
    parameters: []
    return:
      type: System.Int64
    content.vb: >-
      <Comment("The amount of currency awarded to the winner of the trivia game.")>

      Public Property CurrencyReward As Long
  overload: Mewdeko.Modules.Games.Common.TriviaConfig.CurrencyReward*
  attributes:
  - type: Mewdeko.Common.Yml.CommentAttribute
    ctor: Mewdeko.Common.Yml.CommentAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: The amount of currency awarded to the winner of the trivia game.
- uid: Mewdeko.Modules.Games.Common.TriviaConfig.MinimumWinReq
  commentId: P:Mewdeko.Modules.Games.Common.TriviaConfig.MinimumWinReq
  id: MinimumWinReq
  parent: Mewdeko.Modules.Games.Common.TriviaConfig
  langs:
  - csharp
  - vb
  name: MinimumWinReq
  nameWithType: TriviaConfig.MinimumWinReq
  fullName: Mewdeko.Modules.Games.Common.TriviaConfig.MinimumWinReq
  type: Property
  source:
    remote:
      path: src/Mewdeko/Modules/Games/Common/GamesConfig.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: MinimumWinReq
    path: src/Mewdeko/Modules/Games/Common/GamesConfig.cs
    startLine: 66
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Modules.Games.Common
  summary: Users won't be able to start trivia games which have a smaller win requirement than the one specified by this setting.
  example: []
  syntax:
    content: >-
      [Comment("Users won't be able to start trivia games which have a smaller win requirement than the one specified by this setting.")]

      public int MinimumWinReq { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: >-
      <Comment("Users won't be able to start trivia games which have a smaller win requirement than the one specified by this setting.")>

      Public Property MinimumWinReq As Integer
  overload: Mewdeko.Modules.Games.Common.TriviaConfig.MinimumWinReq*
  attributes:
  - type: Mewdeko.Common.Yml.CommentAttribute
    ctor: Mewdeko.Common.Yml.CommentAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Users won't be able to start trivia games which have a smaller win requirement than the one specified by this setting.
references:
- uid: Mewdeko.Modules.Games.Common
  commentId: N:Mewdeko.Modules.Games.Common
  href: Mewdeko.html
  name: Mewdeko.Modules.Games.Common
  nameWithType: Mewdeko.Modules.Games.Common
  fullName: Mewdeko.Modules.Games.Common
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Modules
    name: Modules
    href: Mewdeko.Modules.html
  - name: .
  - uid: Mewdeko.Modules.Games
    name: Games
    href: Mewdeko.Modules.Games.html
  - name: .
  - uid: Mewdeko.Modules.Games.Common
    name: Common
    href: Mewdeko.Modules.Games.Common.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Modules
    name: Modules
    href: Mewdeko.Modules.html
  - name: .
  - uid: Mewdeko.Modules.Games
    name: Games
    href: Mewdeko.Modules.Games.html
  - name: .
  - uid: Mewdeko.Modules.Games.Common
    name: Common
    href: Mewdeko.Modules.Games.Common.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: Mewdeko.Modules.Games.Common.TriviaConfig.Mewdeko.Extensions.Extensions.ThrowIfNull``1(System.String)
  commentId: M:Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  parent: Mewdeko.Extensions.Extensions
  definition: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  name: ThrowIfNull<TriviaConfig>(TriviaConfig, string)
  nameWithType: Extensions.ThrowIfNull<TriviaConfig>(TriviaConfig, string)
  fullName: Mewdeko.Extensions.Extensions.ThrowIfNull<Mewdeko.Modules.Games.Common.TriviaConfig>(Mewdeko.Modules.Games.Common.TriviaConfig, string)
  nameWithType.vb: Extensions.ThrowIfNull(Of TriviaConfig)(TriviaConfig, String)
  fullName.vb: Mewdeko.Extensions.Extensions.ThrowIfNull(Of Mewdeko.Modules.Games.Common.TriviaConfig)(Mewdeko.Modules.Games.Common.TriviaConfig, String)
  name.vb: ThrowIfNull(Of TriviaConfig)(TriviaConfig, String)
  spec.csharp:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(Mewdeko.Modules.Games.Common.TriviaConfig,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: <
  - uid: Mewdeko.Modules.Games.Common.TriviaConfig
    name: TriviaConfig
    href: Mewdeko.Modules.Games.Common.TriviaConfig.html
  - name: '>'
  - name: (
  - uid: Mewdeko.Modules.Games.Common.TriviaConfig
    name: TriviaConfig
    href: Mewdeko.Modules.Games.Common.TriviaConfig.html
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(Mewdeko.Modules.Games.Common.TriviaConfig,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: (
  - name: Of
  - name: " "
  - uid: Mewdeko.Modules.Games.Common.TriviaConfig
    name: TriviaConfig
    href: Mewdeko.Modules.Games.Common.TriviaConfig.html
  - name: )
  - name: (
  - uid: Mewdeko.Modules.Games.Common.TriviaConfig
    name: TriviaConfig
    href: Mewdeko.Modules.Games.Common.TriviaConfig.html
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  commentId: M:Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  isExternal: true
  href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  name: ThrowIfNull<T>(T, string)
  nameWithType: Extensions.ThrowIfNull<T>(T, string)
  fullName: Mewdeko.Extensions.Extensions.ThrowIfNull<T>(T, string)
  nameWithType.vb: Extensions.ThrowIfNull(Of T)(T, String)
  fullName.vb: Mewdeko.Extensions.Extensions.ThrowIfNull(Of T)(T, String)
  name.vb: ThrowIfNull(Of T)(T, String)
  spec.csharp:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Mewdeko.Extensions.Extensions
  commentId: T:Mewdeko.Extensions.Extensions
  parent: Mewdeko.Extensions
  href: Mewdeko.Extensions.Extensions.html
  name: Extensions
  nameWithType: Extensions
  fullName: Mewdeko.Extensions.Extensions
- uid: Mewdeko.Extensions
  commentId: N:Mewdeko.Extensions
  href: Mewdeko.html
  name: Mewdeko.Extensions
  nameWithType: Mewdeko.Extensions
  fullName: Mewdeko.Extensions
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Extensions
    name: Extensions
    href: Mewdeko.Extensions.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Extensions
    name: Extensions
    href: Mewdeko.Extensions.html
- uid: Mewdeko.Modules.Games.Common.TriviaConfig.CurrencyReward*
  commentId: Overload:Mewdeko.Modules.Games.Common.TriviaConfig.CurrencyReward
  href: Mewdeko.Modules.Games.Common.TriviaConfig.html#Mewdeko_Modules_Games_Common_TriviaConfig_CurrencyReward
  name: CurrencyReward
  nameWithType: TriviaConfig.CurrencyReward
  fullName: Mewdeko.Modules.Games.Common.TriviaConfig.CurrencyReward
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: Mewdeko.Modules.Games.Common.TriviaConfig.MinimumWinReq*
  commentId: Overload:Mewdeko.Modules.Games.Common.TriviaConfig.MinimumWinReq
  href: Mewdeko.Modules.Games.Common.TriviaConfig.html#Mewdeko_Modules_Games_Common_TriviaConfig_MinimumWinReq
  name: MinimumWinReq
  nameWithType: TriviaConfig.MinimumWinReq
  fullName: Mewdeko.Modules.Games.Common.TriviaConfig.MinimumWinReq
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
