### YamlMime:ManagedReference
items:
- uid: Mewdeko.Services.RestartConfig
  commentId: T:Mewdeko.Services.RestartConfig
  id: RestartConfig
  parent: Mewdeko.Services
  children:
  - Mewdeko.Services.RestartConfig.#ctor(System.String,System.String)
  - Mewdeko.Services.RestartConfig.Args
  - Mewdeko.Services.RestartConfig.Cmd
  langs:
  - csharp
  - vb
  name: RestartConfig
  nameWithType: RestartConfig
  fullName: Mewdeko.Services.RestartConfig
  type: Class
  source:
    remote:
      path: src/Mewdeko/Services/IBotCredentials.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: RestartConfig
    path: src/Mewdeko/Services/IBotCredentials.cs
    startLine: 150
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services
  summary: Represents configuration for restarting the bot.
  example: []
  syntax:
    content: public class RestartConfig
    content.vb: Public Class RestartConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - Mewdeko.Services.RestartConfig.Mewdeko.Extensions.Extensions.ThrowIfNull``1(System.String)
- uid: Mewdeko.Services.RestartConfig.#ctor(System.String,System.String)
  commentId: M:Mewdeko.Services.RestartConfig.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: Mewdeko.Services.RestartConfig
  langs:
  - csharp
  - vb
  name: RestartConfig(string, string)
  nameWithType: RestartConfig.RestartConfig(string, string)
  fullName: Mewdeko.Services.RestartConfig.RestartConfig(string, string)
  type: Constructor
  source:
    remote:
      path: src/Mewdeko/Services/IBotCredentials.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: .ctor
    path: src/Mewdeko/Services/IBotCredentials.cs
    startLine: 157
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services
  summary: Initializes a new instance of the <xref href="Mewdeko.Services.RestartConfig" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public RestartConfig(string cmd, string args)
    parameters:
    - id: cmd
      type: System.String
      description: The command used for restarting.
    - id: args
      type: System.String
      description: The arguments for restarting.
    content.vb: Public Sub New(cmd As String, args As String)
  overload: Mewdeko.Services.RestartConfig.#ctor*
  nameWithType.vb: RestartConfig.New(String, String)
  fullName.vb: Mewdeko.Services.RestartConfig.New(String, String)
  name.vb: New(String, String)
- uid: Mewdeko.Services.RestartConfig.Cmd
  commentId: P:Mewdeko.Services.RestartConfig.Cmd
  id: Cmd
  parent: Mewdeko.Services.RestartConfig
  langs:
  - csharp
  - vb
  name: Cmd
  nameWithType: RestartConfig.Cmd
  fullName: Mewdeko.Services.RestartConfig.Cmd
  type: Property
  source:
    remote:
      path: src/Mewdeko/Services/IBotCredentials.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: Cmd
    path: src/Mewdeko/Services/IBotCredentials.cs
    startLine: 166
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services
  summary: Gets the command used for restarting.
  example: []
  syntax:
    content: public string Cmd { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Cmd As String
  overload: Mewdeko.Services.RestartConfig.Cmd*
- uid: Mewdeko.Services.RestartConfig.Args
  commentId: P:Mewdeko.Services.RestartConfig.Args
  id: Args
  parent: Mewdeko.Services.RestartConfig
  langs:
  - csharp
  - vb
  name: Args
  nameWithType: RestartConfig.Args
  fullName: Mewdeko.Services.RestartConfig.Args
  type: Property
  source:
    remote:
      path: src/Mewdeko/Services/IBotCredentials.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: Args
    path: src/Mewdeko/Services/IBotCredentials.cs
    startLine: 171
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services
  summary: Gets the arguments for restarting.
  example: []
  syntax:
    content: public string Args { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Args As String
  overload: Mewdeko.Services.RestartConfig.Args*
references:
- uid: Mewdeko.Services
  commentId: N:Mewdeko.Services
  href: Mewdeko.html
  name: Mewdeko.Services
  nameWithType: Mewdeko.Services
  fullName: Mewdeko.Services
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Services
    name: Services
    href: Mewdeko.Services.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Services
    name: Services
    href: Mewdeko.Services.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: Mewdeko.Services.RestartConfig.Mewdeko.Extensions.Extensions.ThrowIfNull``1(System.String)
  commentId: M:Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  parent: Mewdeko.Extensions.Extensions
  definition: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  name: ThrowIfNull<RestartConfig>(RestartConfig, string)
  nameWithType: Extensions.ThrowIfNull<RestartConfig>(RestartConfig, string)
  fullName: Mewdeko.Extensions.Extensions.ThrowIfNull<Mewdeko.Services.RestartConfig>(Mewdeko.Services.RestartConfig, string)
  nameWithType.vb: Extensions.ThrowIfNull(Of RestartConfig)(RestartConfig, String)
  fullName.vb: Mewdeko.Extensions.Extensions.ThrowIfNull(Of Mewdeko.Services.RestartConfig)(Mewdeko.Services.RestartConfig, String)
  name.vb: ThrowIfNull(Of RestartConfig)(RestartConfig, String)
  spec.csharp:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(Mewdeko.Services.RestartConfig,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: <
  - uid: Mewdeko.Services.RestartConfig
    name: RestartConfig
    href: Mewdeko.Services.RestartConfig.html
  - name: '>'
  - name: (
  - uid: Mewdeko.Services.RestartConfig
    name: RestartConfig
    href: Mewdeko.Services.RestartConfig.html
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(Mewdeko.Services.RestartConfig,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: (
  - name: Of
  - name: " "
  - uid: Mewdeko.Services.RestartConfig
    name: RestartConfig
    href: Mewdeko.Services.RestartConfig.html
  - name: )
  - name: (
  - uid: Mewdeko.Services.RestartConfig
    name: RestartConfig
    href: Mewdeko.Services.RestartConfig.html
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  commentId: M:Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
  isExternal: true
  href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  name: ThrowIfNull<T>(T, string)
  nameWithType: Extensions.ThrowIfNull<T>(T, string)
  fullName: Mewdeko.Extensions.Extensions.ThrowIfNull<T>(T, string)
  nameWithType.vb: Extensions.ThrowIfNull(Of T)(T, String)
  fullName.vb: Mewdeko.Extensions.Extensions.ThrowIfNull(Of T)(T, String)
  name.vb: ThrowIfNull(Of T)(T, String)
  spec.csharp:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: Mewdeko.Extensions.Extensions.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull
    href: Mewdeko.Extensions.Extensions.html#Mewdeko_Extensions_Extensions_ThrowIfNull__1___0_System_String_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Mewdeko.Extensions.Extensions
  commentId: T:Mewdeko.Extensions.Extensions
  parent: Mewdeko.Extensions
  href: Mewdeko.Extensions.Extensions.html
  name: Extensions
  nameWithType: Extensions
  fullName: Mewdeko.Extensions.Extensions
- uid: Mewdeko.Extensions
  commentId: N:Mewdeko.Extensions
  href: Mewdeko.html
  name: Mewdeko.Extensions
  nameWithType: Mewdeko.Extensions
  fullName: Mewdeko.Extensions
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Extensions
    name: Extensions
    href: Mewdeko.Extensions.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Extensions
    name: Extensions
    href: Mewdeko.Extensions.html
- uid: Mewdeko.Services.RestartConfig
  commentId: T:Mewdeko.Services.RestartConfig
  parent: Mewdeko.Services
  href: Mewdeko.Services.RestartConfig.html
  name: RestartConfig
  nameWithType: RestartConfig
  fullName: Mewdeko.Services.RestartConfig
- uid: Mewdeko.Services.RestartConfig.#ctor*
  commentId: Overload:Mewdeko.Services.RestartConfig.#ctor
  href: Mewdeko.Services.RestartConfig.html#Mewdeko_Services_RestartConfig__ctor_System_String_System_String_
  name: RestartConfig
  nameWithType: RestartConfig.RestartConfig
  fullName: Mewdeko.Services.RestartConfig.RestartConfig
  nameWithType.vb: RestartConfig.New
  fullName.vb: Mewdeko.Services.RestartConfig.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Mewdeko.Services.RestartConfig.Cmd*
  commentId: Overload:Mewdeko.Services.RestartConfig.Cmd
  href: Mewdeko.Services.RestartConfig.html#Mewdeko_Services_RestartConfig_Cmd
  name: Cmd
  nameWithType: RestartConfig.Cmd
  fullName: Mewdeko.Services.RestartConfig.Cmd
- uid: Mewdeko.Services.RestartConfig.Args*
  commentId: Overload:Mewdeko.Services.RestartConfig.Args
  href: Mewdeko.Services.RestartConfig.html#Mewdeko_Services_RestartConfig_Args
  name: Args
  nameWithType: RestartConfig.Args
  fullName: Mewdeko.Services.RestartConfig.Args
