### YamlMime:ManagedReference
items:
- uid: Mewdeko.Services.Settings
  commentId: N:Mewdeko.Services.Settings
  id: Mewdeko.Services.Settings
  children:
  - Mewdeko.Services.Settings.BotConfigService
  - Mewdeko.Services.Settings.ConfigParsers
  - Mewdeko.Services.Settings.ConfigPrinters
  - Mewdeko.Services.Settings.ConfigServiceBase`1
  - Mewdeko.Services.Settings.IConfigService
  - Mewdeko.Services.Settings.SettingParser`1
  langs:
  - csharp
  - vb
  name: Mewdeko.Services.Settings
  nameWithType: Mewdeko.Services.Settings
  fullName: Mewdeko.Services.Settings
  type: Namespace
  assemblies:
  - Mewdeko
references:
- uid: Mewdeko.Services.Settings.BotConfigService
  commentId: T:Mewdeko.Services.Settings.BotConfigService
  parent: Mewdeko.Services.Settings
  href: Mewdeko.Services.Settings.BotConfigService.html
  name: BotConfigService
  nameWithType: BotConfigService
  fullName: Mewdeko.Services.Settings.BotConfigService
- uid: Mewdeko.Services.Settings.ConfigParsers
  commentId: T:Mewdeko.Services.Settings.ConfigParsers
  href: Mewdeko.Services.Settings.ConfigParsers.html
  name: ConfigParsers
  nameWithType: ConfigParsers
  fullName: Mewdeko.Services.Settings.ConfigParsers
- uid: Mewdeko.Services.Settings.ConfigPrinters
  commentId: T:Mewdeko.Services.Settings.ConfigPrinters
  href: Mewdeko.Services.Settings.ConfigPrinters.html
  name: ConfigPrinters
  nameWithType: ConfigPrinters
  fullName: Mewdeko.Services.Settings.ConfigPrinters
- uid: Mewdeko.Services.Settings.ConfigServiceBase`1
  commentId: T:Mewdeko.Services.Settings.ConfigServiceBase`1
  href: Mewdeko.Services.Settings.ConfigServiceBase-1.html
  name: ConfigServiceBase<TSettings>
  nameWithType: ConfigServiceBase<TSettings>
  fullName: Mewdeko.Services.Settings.ConfigServiceBase<TSettings>
  nameWithType.vb: ConfigServiceBase(Of TSettings)
  fullName.vb: Mewdeko.Services.Settings.ConfigServiceBase(Of TSettings)
  name.vb: ConfigServiceBase(Of TSettings)
  spec.csharp:
  - uid: Mewdeko.Services.Settings.ConfigServiceBase`1
    name: ConfigServiceBase
    href: Mewdeko.Services.Settings.ConfigServiceBase-1.html
  - name: <
  - name: TSettings
  - name: '>'
  spec.vb:
  - uid: Mewdeko.Services.Settings.ConfigServiceBase`1
    name: ConfigServiceBase
    href: Mewdeko.Services.Settings.ConfigServiceBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TSettings
  - name: )
- uid: Mewdeko.Services.Settings.IConfigService
  commentId: T:Mewdeko.Services.Settings.IConfigService
  parent: Mewdeko.Services.Settings
  href: Mewdeko.Services.Settings.IConfigService.html
  name: IConfigService
  nameWithType: IConfigService
  fullName: Mewdeko.Services.Settings.IConfigService
- uid: Mewdeko.Services.Settings.SettingParser`1
  commentId: T:Mewdeko.Services.Settings.SettingParser`1
  href: Mewdeko.Services.Settings.SettingParser-1.html
  name: SettingParser<TData>
  nameWithType: SettingParser<TData>
  fullName: Mewdeko.Services.Settings.SettingParser<TData>
  nameWithType.vb: SettingParser(Of TData)
  fullName.vb: Mewdeko.Services.Settings.SettingParser(Of TData)
  name.vb: SettingParser(Of TData)
  spec.csharp:
  - uid: Mewdeko.Services.Settings.SettingParser`1
    name: SettingParser
    href: Mewdeko.Services.Settings.SettingParser-1.html
  - name: <
  - name: TData
  - name: '>'
  spec.vb:
  - uid: Mewdeko.Services.Settings.SettingParser`1
    name: SettingParser
    href: Mewdeko.Services.Settings.SettingParser-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TData
  - name: )
- uid: Mewdeko.Services.Settings
  commentId: N:Mewdeko.Services.Settings
  href: Mewdeko.html
  name: Mewdeko.Services.Settings
  nameWithType: Mewdeko.Services.Settings
  fullName: Mewdeko.Services.Settings
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Services
    name: Services
    href: Mewdeko.Services.html
  - name: .
  - uid: Mewdeko.Services.Settings
    name: Settings
    href: Mewdeko.Services.Settings.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Services
    name: Services
    href: Mewdeko.Services.html
  - name: .
  - uid: Mewdeko.Services.Settings
    name: Settings
    href: Mewdeko.Services.Settings.html
