### YamlMime:ManagedReference
items:
- uid: Mewdeko.Services.Settings.ConfigPrinters
  commentId: T:Mewdeko.Services.Settings.ConfigPrinters
  id: ConfigPrinters
  parent: Mewdeko.Services.Settings
  children:
  - Mewdeko.Services.Settings.ConfigPrinters.Color(SkiaSharp.SKColor)
  - Mewdeko.Services.Settings.ConfigPrinters.Culture(System.Globalization.CultureInfo)
  - Mewdeko.Services.Settings.ConfigPrinters.ToString``1(``0)
  langs:
  - csharp
  - vb
  name: ConfigPrinters
  nameWithType: ConfigPrinters
  fullName: Mewdeko.Services.Settings.ConfigPrinters
  type: Class
  source:
    remote:
      path: src/Mewdeko/Services/Settings/ConfigParsers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: ConfigPrinters
    path: src/Mewdeko/Services/Settings/ConfigParsers.cs
    startLine: 43
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services.Settings
  summary: Custom setting value printers for types which don't have them by default
  example: []
  syntax:
    content: public static class ConfigPrinters
    content.vb: Public Module ConfigPrinters
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Mewdeko.Services.Settings.ConfigPrinters.ToString``1(``0)
  commentId: M:Mewdeko.Services.Settings.ConfigPrinters.ToString``1(``0)
  id: ToString``1(``0)
  parent: Mewdeko.Services.Settings.ConfigPrinters
  langs:
  - csharp
  - vb
  name: ToString<TAny>(TAny?)
  nameWithType: ConfigPrinters.ToString<TAny>(TAny?)
  fullName: Mewdeko.Services.Settings.ConfigPrinters.ToString<TAny>(TAny?)
  type: Method
  source:
    remote:
      path: src/Mewdeko/Services/Settings/ConfigParsers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: ToString
    path: src/Mewdeko/Services/Settings/ConfigParsers.cs
    startLine: 51
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services.Settings
  summary: Converts the input object to its string representation.
  example: []
  syntax:
    content: public static string ToString<TAny>(TAny? input)
    parameters:
    - id: input
      type: '{TAny}'
      description: The input object.
    typeParameters:
    - id: TAny
      description: The type of the input object.
    return:
      type: System.String
      description: The string representation of the input object, or "null" if the input is null.
    content.vb: Public Shared Function ToString(Of TAny)(input As TAny) As String
  overload: Mewdeko.Services.Settings.ConfigPrinters.ToString*
  nameWithType.vb: ConfigPrinters.ToString(Of TAny)(TAny)
  fullName.vb: Mewdeko.Services.Settings.ConfigPrinters.ToString(Of TAny)(TAny)
  name.vb: ToString(Of TAny)(TAny)
- uid: Mewdeko.Services.Settings.ConfigPrinters.Color(SkiaSharp.SKColor)
  commentId: M:Mewdeko.Services.Settings.ConfigPrinters.Color(SkiaSharp.SKColor)
  id: Color(SkiaSharp.SKColor)
  parent: Mewdeko.Services.Settings.ConfigPrinters
  langs:
  - csharp
  - vb
  name: Color(SKColor)
  nameWithType: ConfigPrinters.Color(SKColor)
  fullName: Mewdeko.Services.Settings.ConfigPrinters.Color(SkiaSharp.SKColor)
  type: Method
  source:
    remote:
      path: src/Mewdeko/Services/Settings/ConfigParsers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: Color
    path: src/Mewdeko/Services/Settings/ConfigParsers.cs
    startLine: 58
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services.Settings
  summary: Converts the SKColor to its hexadecimal representation.
  example: []
  syntax:
    content: public static string Color(SKColor color)
    parameters:
    - id: color
      type: SkiaSharp.SKColor
      description: The SKColor to convert.
    return:
      type: System.String
      description: The hexadecimal representation of the SKColor.
    content.vb: Public Shared Function Color(color As SKColor) As String
  overload: Mewdeko.Services.Settings.ConfigPrinters.Color*
- uid: Mewdeko.Services.Settings.ConfigPrinters.Culture(System.Globalization.CultureInfo)
  commentId: M:Mewdeko.Services.Settings.ConfigPrinters.Culture(System.Globalization.CultureInfo)
  id: Culture(System.Globalization.CultureInfo)
  parent: Mewdeko.Services.Settings.ConfigPrinters
  langs:
  - csharp
  - vb
  name: Culture(CultureInfo)
  nameWithType: ConfigPrinters.Culture(CultureInfo)
  fullName: Mewdeko.Services.Settings.ConfigPrinters.Culture(System.Globalization.CultureInfo)
  type: Method
  source:
    remote:
      path: src/Mewdeko/Services/Settings/ConfigParsers.cs
      branch: psqldeko
      repo: https://github.com/Sylveon76/Mewdeko.git
    id: Culture
    path: src/Mewdeko/Services/Settings/ConfigParsers.cs
    startLine: 66
  assemblies:
  - Mewdeko
  namespace: Mewdeko.Services.Settings
  summary: Converts the CultureInfo to its name.
  example: []
  syntax:
    content: public static string Culture(CultureInfo culture)
    parameters:
    - id: culture
      type: System.Globalization.CultureInfo
      description: The culture to convert
    return:
      type: System.String
      description: The culture in string form
    content.vb: Public Shared Function Culture(culture As CultureInfo) As String
  overload: Mewdeko.Services.Settings.ConfigPrinters.Culture*
references:
- uid: Mewdeko.Services.Settings
  commentId: N:Mewdeko.Services.Settings
  href: Mewdeko.html
  name: Mewdeko.Services.Settings
  nameWithType: Mewdeko.Services.Settings
  fullName: Mewdeko.Services.Settings
  spec.csharp:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Services
    name: Services
    href: Mewdeko.Services.html
  - name: .
  - uid: Mewdeko.Services.Settings
    name: Settings
    href: Mewdeko.Services.Settings.html
  spec.vb:
  - uid: Mewdeko
    name: Mewdeko
    href: Mewdeko.html
  - name: .
  - uid: Mewdeko.Services
    name: Services
    href: Mewdeko.Services.html
  - name: .
  - uid: Mewdeko.Services.Settings
    name: Settings
    href: Mewdeko.Services.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Mewdeko.Services.Settings.ConfigPrinters.ToString*
  commentId: Overload:Mewdeko.Services.Settings.ConfigPrinters.ToString
  href: Mewdeko.Services.Settings.ConfigPrinters.html#Mewdeko_Services_Settings_ConfigPrinters_ToString__1___0_
  name: ToString
  nameWithType: ConfigPrinters.ToString
  fullName: Mewdeko.Services.Settings.ConfigPrinters.ToString
- uid: '{TAny}'
  commentId: '!:TAny'
  definition: TAny
  name: TAny
  nameWithType: TAny
  fullName: TAny
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: TAny
  commentId: '!:TAny'
  name: TAny
  nameWithType: TAny
  fullName: TAny
- uid: Mewdeko.Services.Settings.ConfigPrinters.Color*
  commentId: Overload:Mewdeko.Services.Settings.ConfigPrinters.Color
  href: Mewdeko.Services.Settings.ConfigPrinters.html#Mewdeko_Services_Settings_ConfigPrinters_Color_SkiaSharp_SKColor_
  name: Color
  nameWithType: ConfigPrinters.Color
  fullName: Mewdeko.Services.Settings.ConfigPrinters.Color
- uid: SkiaSharp.SKColor
  commentId: T:SkiaSharp.SKColor
  parent: SkiaSharp
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/skiasharp.skcolor
  name: SKColor
  nameWithType: SKColor
  fullName: SkiaSharp.SKColor
- uid: SkiaSharp
  commentId: N:SkiaSharp
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/skiasharp
  name: SkiaSharp
  nameWithType: SkiaSharp
  fullName: SkiaSharp
- uid: Mewdeko.Services.Settings.ConfigPrinters.Culture*
  commentId: Overload:Mewdeko.Services.Settings.ConfigPrinters.Culture
  href: Mewdeko.Services.Settings.ConfigPrinters.html#Mewdeko_Services_Settings_ConfigPrinters_Culture_System_Globalization_CultureInfo_
  name: Culture
  nameWithType: ConfigPrinters.Culture
  fullName: Mewdeko.Services.Settings.ConfigPrinters.Culture
- uid: System.Globalization.CultureInfo
  commentId: T:System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.globalization.cultureinfo
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Globalization
  commentId: N:System.Globalization
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Globalization
  nameWithType: System.Globalization
  fullName: System.Globalization
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Globalization
    name: Globalization
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.globalization
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Globalization
    name: Globalization
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.globalization
